---

- name: Download magerun phar file
  get_url:
    url: "https://files.magerun.net/n98-magerun{{ '2' if magento_version == '2' else '' }}-{{ magerun_version }}.phar"
    dest: /tmp/magerun.phar
    force: yes

- name: "Copy magerun into {{ magerun_path }}"
  become: yes
  copy:
    src: /tmp/magerun.phar
    remote_src: yes
    dest: "{{ magerun_path }}"

- name: Set permissions on magerun
  become: yes
  file:
    path: /tmp/magerun.phar
    mode: "a+x"