---

# Get Download URL Based upon Magento version
- set_fact:
    download_url: "{{ magerun1_url if magento_version == 1 else magerun2_url }}"

- name: Download magerun phar file
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/magerun.phar

- name: "Copy magerun into {{ magerun_path }}"
  become: yes
  shell: "cp /tmp/magerun.phar {{ magerun_path }}"
  args:
    creates: "{{ magerun_path }}"

- name: Set permissions on magerun
  become: yes
  file:
    path: "{{ magerun_path }}"
    mode: "a+x"