---

- name: Check if n98-magerun is installed
  stat:
    path: "{{ magerun_path }}"
  register: magerun_installed
  tags:
    - magerun

- include: install.yml
  when: not magerun_installed.stat.exists
  tags:
    - magerun

- name: Update n98-magerun if required
  become: yes
  command: magerun self-update
  register: magerun_update
  changed_when: "'You are using the latest n98-magerun version' in magerun_update.stdout_lines"
  when: magerun_use_latest
  tags:
    - magerun