---

- name: Check if n98-magerun is installed
  stat:
    path: "{{ magerun_path }}"
  register: magerun_installed
  tags:
    - magerun

- name: Ensure correct n98-magerun version
  command: "{{ magerun_path }} -V"
  register: magerun_installed_version
  when: magerun_installed.stat.exists
  changed_when: false
  tags:
    - magerun

- include: install.yml
  when: not magerun_installed.stat.exists or magerun_version not in magerun_installed_version.stdout_lines
  tags:
    - magerun