---

# Get Download URL Based upon Magento version
- set_fact:
    download_url: "{{ magerun1_url if magento_version == 1 else magerun2_url }}"
  tags:
    - magerun

- name: Download magerun phar file
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/magerun.phar
  tags:
    - magerun

- name: Copy magerun into /usr/loca/bin
  become: yes
  shell: "cp /tmp/magerun.phar /usr/local/bin/magerun"
  args:
    creates: /usr/local/bin/magerun
  tags:
    - magerun

- name: Set permissions on magerun
  become: yes
  file:
    path: /usr/local/bin/magerun
    mode: "a+x"
  tags:
    - magerun
